# Generated by Django 3.1 on 2021-01-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podo_app', '0006_add_likeproduct_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='products_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='products_sold',
            field=models.IntegerField(default=0),
        ),
    ]
