# Generated by Django 3.1 on 2021-01-03 14:43

from django.db import migrations, models
import podo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('podo_app', '0007_auto_20210102_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=podo_app.models.productImagePath),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=podo_app.models.profileImagePath),
        ),
    ]
