# Generated by Django 3.1 on 2021-01-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podo_app', '0008_auto_20210103_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
