# Generated by Django 3.1 on 2021-01-07 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podo_app', '0011_auto_20210108_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_review', models.PositiveSmallIntegerField(default=0)),
                ('buyer_review', models.PositiveSmallIntegerField(default=0)),
                ('chatroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='podo_app.chatroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggest_price', models.PositiveSmallIntegerField()),
                ('confirm', models.BooleanField(default=False)),
                ('chatroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggest_price', to='podo_app.chatroom')),
                ('will_buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggest_price', to='podo_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
