# Generated by Django 3.1 on 2021-01-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podo_app', '0012_suggestprice_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestprice',
            name='chatroom',
        ),
        migrations.AddField(
            model_name='suggestprice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggest_prices', to='podo_app.product'),
        ),
    ]
