# Generated by Django 3.1 on 2021-01-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podo_app', '0013_auto_20210108_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DIGITAL', 'DIGITAL'), ('BOOK', 'BOOK'), ('CLOTHES', 'CLOTHES'), ('BEAUTY', 'BEAUTY'), ('FURNITURE', 'FURNITURE'), ('KITCHEN UTENSILS', 'KITCHEN UTENSILS')], max_length=50),
        ),
    ]
