# Generated by Django 3.1 on 2021-01-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podo_app', '0014_auto_20210108_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
