# Generated by Django 3.1 on 2021-01-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podo_app', '0016_auto_20210109_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatrooms', to='podo_app.product'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='will_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatrooms', to='podo_app.profile'),
        ),
        migrations.AlterField(
            model_name='likeproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_profiles', to='podo_app.product'),
        ),
        migrations.AlterField(
            model_name='likeproduct',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_products', to='podo_app.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='written_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='podo_app.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='here_products', to='podo_app.city'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggest_prices', to='podo_app.product'),
        ),
        migrations.AlterField(
            model_name='suggestprice',
            name='will_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggest_price', to='podo_app.profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='chatroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='podo_app.chatroom'),
        ),
    ]
