name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-host:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
            MYSQL_DATABASE: 'podo_db'
            MYSQL_USER: 'waffle-backend'
            MYSQL_PASSWORD: 'seminar'
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Verify MySQL connection
      run: |
        mysql --version
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword --default_character_set=utf8 -e "SHOW DATABASES"
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        cd podo_server
        coverage run manage.py test
        coverage report
      env:
        SYSTEM_ENV: GITHUB_WORKFLOW
